# Generated by Django 4.0.2 on 2022-06-13 09:33

import uuid

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("confidence", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name_plural": "Activity Annotations",
                "ordering": ("-modified",),
            },
        ),
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("comments", models.TextField(blank=True, null=True, verbose_name="Additional notes")),
            ],
            options={
                "verbose_name_plural": "Activity Types",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Annotator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("type", models.CharField(choices=[("human", "Human"), ("bot", "Bot")], max_length=10)),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("version", models.CharField(max_length=10)),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("object_detection", "Object Detection"),
                            ("object_identification", "Object Identification"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("model_api_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("model_file_url", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("w", models.FloatField()),
                ("h", models.FloatField()),
                ("confidence", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name_plural": "Bounding Boxes",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="CameraStationAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("action", models.TextField(unique=True, verbose_name="Last action taken")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[("animal", "animal"), ("vehicle", "vehicle"), ("person", "person")], max_length=10
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name_plural": "Category Annotations",
                "ordering": ("-modified",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalCameraStationAction",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("action", models.TextField(db_index=True, verbose_name="Last action taken")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical camera station action",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUpload",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("date_retrieved", models.DateTimeField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("dropbox_folder_name", models.TextField(db_index=True)),
                ("dropbox_folder_path", models.TextField(db_index=True)),
                ("dropbox_request_id", models.CharField(max_length=50)),
                ("dropbox_request_url", models.URLField()),
                ("dropbox_request_open", models.BooleanField(default=True)),
                ("dropbox_folder_id", models.CharField(blank=True, max_length=50, null=True)),
                ("dropbox_share_url", models.URLField(blank=True, null=True)),
                ("upload_complete", models.BooleanField(default=False, verbose_name="Upload to Dropbox complete?")),
                ("processed", models.BooleanField(default=False, verbose_name="Processed upload?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical upload",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("dropbox_file_name", models.TextField()),
                ("dropbox_file_path", models.TextField()),
                ("dropbox_file_path_display", models.TextField()),
                ("dropbox_content_hash", models.CharField(max_length=100)),
                ("dropbox_file_id", models.CharField(max_length=50)),
                ("dropbox_share_url", models.URLField(blank=True, null=True)),
                ("file_size", models.BigIntegerField()),
                ("is_video", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("trigger_timestamp", models.DateTimeField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("thumbnail_gcloud_path", models.CharField(blank=True, max_length=250, null=True)),
                ("social_media_worthy", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ("trigger_timestamp", "-created"),
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("confidence", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name_plural": "Species Annotations",
                "ordering": ("-modified",),
            },
        ),
        migrations.CreateModel(
            name="SpeciesName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="Common Name")),
                ("scientific_name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "Species List",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_retrieved", models.DateTimeField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("dropbox_folder_name", models.TextField(unique=True)),
                ("dropbox_folder_path", models.TextField(unique=True)),
                ("dropbox_request_id", models.CharField(max_length=50)),
                ("dropbox_request_url", models.URLField()),
                ("dropbox_request_open", models.BooleanField(default=True)),
                ("dropbox_folder_id", models.CharField(blank=True, max_length=50, null=True)),
                ("dropbox_share_url", models.URLField(blank=True, null=True)),
                ("upload_complete", models.BooleanField(default=False, verbose_name="Upload to Dropbox complete?")),
                ("processed", models.BooleanField(default=False, verbose_name="Processed upload?")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
