# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.2 on 2022-06-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="camera_station",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="locations.camerastation"),
        ),
        migrations.AddField(
            model_name="upload",
            name="last_action",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="images.camerastationaction"),
        ),
    ]
