# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.2 on 2022-06-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("images", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="volunteer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="species",
            name="accepted_by",
            field=models.ManyToManyField(blank=True, related_name="accepted_species_annotation", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="species",
            name="bounding_box",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.boundingbox"),
        ),
        migrations.AddField(
            model_name="species",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_species_annotation",
                to="images.annotator",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="images.speciesname"),
        ),
        migrations.AddField(
            model_name="species",
            name="rejected_by",
            field=models.ManyToManyField(blank=True, related_name="rejected_species_annotation", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="activity_checked_by",
            field=models.ManyToManyField(blank=True, related_name="checked_bbox_for_activity", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="activity_skipped_by",
            field=models.ManyToManyField(blank=True, related_name="skipped_bbox_for_activity", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="bbox_checked_by",
            field=models.ManyToManyField(blank=True, related_name="checked_bbox_for_images", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="bbox_skipped_by",
            field=models.ManyToManyField(blank=True, related_name="skipped_bbox_for_images", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="species_checked_by",
            field=models.ManyToManyField(blank=True, related_name="checked_bbox_for_species", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="species_skipped_by",
            field=models.ManyToManyField(blank=True, related_name="skipped_bbox_for_species", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="image",
            name="upload",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="images.upload"),
        ),
        migrations.AddField(
            model_name="historicalupload",
            name="camera_station",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.camerastation",
            ),
        ),
        migrations.AddField(
            model_name="historicalupload",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalupload",
            name="last_action",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="images.camerastationaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalupload",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcamerastationaction",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="accepted_by",
            field=models.ManyToManyField(
                blank=True, related_name="accepted_category_annotation", to="images.Annotator"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="bounding_box",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.boundingbox"),
        ),
        migrations.AddField(
            model_name="category",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_category_annotation",
                to="images.annotator",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="rejected_by",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_category_annotation", to="images.Annotator"
            ),
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="accepted_by",
            field=models.ManyToManyField(blank=True, related_name="accepted_annotation", to="images.Annotator"),
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="created_annotation", to="images.annotator"
            ),
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="image",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.image"),
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="rejected_by",
            field=models.ManyToManyField(blank=True, related_name="rejected_annotation", to="images.Annotator"),
        ),
        migrations.AlterUniqueTogether(
            name="bot",
            unique_together={("name", "version")},
        ),
        migrations.AddField(
            model_name="annotator",
            name="bot",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="images.bot"
            ),
        ),
        migrations.AddField(
            model_name="annotator",
            name="human",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="accepted_by",
            field=models.ManyToManyField(
                blank=True, related_name="accepted_activity_annotation", to="images.Annotator"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="bounding_box",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.boundingbox"),
        ),
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_activity_annotation",
                to="images.annotator",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="images.activitytype"),
        ),
        migrations.AddField(
            model_name="activity",
            name="rejected_by",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_activity_annotation", to="images.Annotator"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="upload",
            unique_together={("camera_station", "date_retrieved")},
        ),
    ]
