# Generated by Django 4.0.6 on 2022-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcamerastationaction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical camera station action",
                "verbose_name_plural": "historical camera station actions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalupload",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical upload",
                "verbose_name_plural": "historical uploads",
            },
        ),
        migrations.AlterField(
            model_name="historicalcamerastationaction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalupload",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
