# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2022-08-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_historicalcamerastationaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesname',
            options={'ordering': ('name', '-created'), 'verbose_name_plural': 'Species List'},
        ),
    ]
