# Generated by Django 4.0.6 on 2022-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_speciesname_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcamerastationaction',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical camera station action'},
        ),
        migrations.AlterModelOptions(
            name='historicalupload',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical upload'},
        ),
        migrations.AlterField(
            model_name='historicalcamerastationaction',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalupload',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
