# Generated by Django 4.0.6 on 2022-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_historicalcamerastationaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='threshold',
            field=models.FloatField(default=0.05),
        ),
    ]
