# Generated by Django 4.0.6 on 2022-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_bot_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='upload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1, verbose_name='Priority'),
        ),
    ]
