# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-01-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_historicalupload_priority_upload_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='category',
            field=models.CharField(choices=[('animal', 'animal'), ('human', 'human')], default='animal', max_length=10),
        ),
    ]
