# Generated by Django 4.0.6 on 2023-05-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_activitytype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='images.upload'),
        ),
    ]
