# Generated by Django 4.0.6 on 2023-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='time_error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='time_error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
