# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-07-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_historicalupload_time_error_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='time_fix_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='time_fix_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
