# Generated by Django 4.0.6 on 2023-07-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_historicalupload_time_fix_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='staff_review_needed',
            field=models.BooleanField(default=False),
        ),
    ]
