# Generated by Django 4.0.6 on 2023-07-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_historicalupload_time_fix_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalupload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=1, verbose_name='Priority'),
        ),
    ]
