# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-07-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_image_staff_review_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalupload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=1, verbose_name='Priority'),
        ),
    ]
