# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-07-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_alter_historicalupload_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='activity_pipeline_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='category_pipeline_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='has_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='has_humans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='has_vehicles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='has_wild_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='species_pipeline_complete',
            field=models.BooleanField(default=False),
        ),
    ]
