# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-09-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_image_activity_pipeline_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='engagement_info_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='total_activity_annotations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='total_category_annotations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='total_species_annotations',
            field=models.IntegerField(null=True),
        ),
    ]
