# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_annotator_engagement_info_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='use_precomputed_flags',
            field=models.BooleanField(default=False),
        ),
    ]
