# Generated by Django 4.0.6 on 2023-10-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_image_use_precomputed_flags'),
        ('images', '0017_speciesname_species_group'),
    ]

    operations = [
    ]
