# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-10-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_image_use_precomputed_flags'),
        ('images', '0017_speciesname_species_group'),
    ]

    operations = [
    ]
