# Generated by Django 4.0.6 on 2023-10-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_merge_20231002_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('animal', 'animal'), ('vehicle', 'vehicle'), ('person', 'person'), ('Unannotated', 'Unannotated')], max_length=12),
        ),
    ]
