# Generated by Django 4.0.6 on 2023-10-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalupload',
            name='time_error_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalupload',
            name='time_fix_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time_error_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time_fix_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
