# Generated by Django 4.0.6 on 2023-10-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesname',
            name='species_group',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('WILD', 'Wild Animal'), ('DOMESTIC', 'Domestic Animal'), ('VEHICLE', 'Vehicle'), ('OTHER', 'Other')], default=None, max_length=250, null=True, verbose_name='Species Group'),
        ),
    ]
