# Generated by Django 4.0.6 on 2023-10-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingbox',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounding_boxes', to='images.image'),
        ),
    ]
