# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-11-28 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_alter_speciesname_species_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationCounter',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(choices=[('category', 'category'), ('species', 'species'), ('activity', 'activity')], max_length=10)),
                ('annotation_count', models.IntegerField()),
                ('image_count', models.IntegerField()),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recent_annotations', to='images.annotator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
