# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-11-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_annotationcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesname',
            name='is_bird',
            field=models.BooleanField(default=False),
        ),
    ]
