# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-12-11 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_speciesname_is_bird'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('years', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('daylight_savings', models.DateField(null=True)),
                ('applied_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='time_correction_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalupload',
            name='time_correction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='images.timecorrection'),
        ),
        migrations.AddField(
            model_name='upload',
            name='time_correction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='images.timecorrection'),
        ),
    ]
