# Generated by Django 4.0.6 on 2024-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_timecorrection_image_time_correction_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='validity',
            field=models.CharField(choices=[('INVALID', 'Invalid'), ('UNCERTAIN', 'Uncertain'), ('VALID', 'Valid')], default=None, max_length=250, null=True, verbose_name='Validity'),
        ),
    ]
