# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-01-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_boundingbox_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='species_ai_detections',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
