# Generated by Django 4.0.6 on 2024-01-18 02:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_boundingbox_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='species_ai_detections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), null=True, size=None),
        ),
    ]
