# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_image_species_ai_detections'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesname',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
