# Generated by Django 4.0.6 on 2024-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0026_speciesname_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingbox',
            name='validity',
            field=models.CharField(choices=[('INVALID', 'Invalid'), ('UNCERTAIN', 'Uncertain'), ('VALID', 'Valid')], default='UNCERTAIN', max_length=250, null=True, verbose_name='Validity'),
        ),
    ]
