# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-04-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_alter_upload_time_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='confidence_threshold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='has_cats',
            field=models.BooleanField(default=False),
        ),
    ]
