# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_alter_upload_time_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='dropbox_direct_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalupload',
            name='upload_method',
            field=models.CharField(choices=[('E', 'Upload via Dropbox external link'), ('D', 'Upload from Wildepod Dropbox account (Wildepod Credentials Required!)')], default='E', max_length=1, verbose_name='Upload Method'),
        ),
        migrations.AddField(
            model_name='upload',
            name='dropbox_direct_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_method',
            field=models.CharField(choices=[('E', 'Upload via Dropbox external link'), ('D', 'Upload from Wildepod Dropbox account (Wildepod Credentials Required!)')], default='E', max_length=1, verbose_name='Upload Method'),
        ),
    ]
