# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_boundingbox_confidence_threshold_image_has_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='has_bbox_above_confidence_threshold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='has_uncertain_bbox',
            field=models.BooleanField(default=False),
        ),
    ]
