# Generated by Django 4.0.6 on 2024-04-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_image_has_bbox_above_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='context_image_gcloud_paths',
            field=models.TextField(null=True),
        ),
    ]
