# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-05-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_historicalupload_dropbox_direct_url_and_more'),
        ('images', '0032_alter_historicalupload_priority_and_more'),
    ]

    operations = [
    ]
