# Generated by Django 4.0.6 on 2024-04-27 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0032_alter_historicalupload_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pipeline_name', models.CharField(choices=[('SPECIES', 'Species'), ('ACTIVITY_HUMAN', 'Human Activity'), ('ACTIVITY_ANIMAL', 'Animal Activity')], default='SPECIES', max_length=250, verbose_name='Pipeline')),
                ('assigned_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to_annotator', to='images.annotator')),
                ('images', models.ManyToManyField(blank=True, related_name='queue_images', to='images.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
