# Generated by Django 4.0.6 on 2024-05-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_historicalupload_dropbox_direct_url_and_more'),
        ('images', '0032_alter_historicalupload_priority_and_more'),
    ]

    operations = [
    ]
