# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-05-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0033_imagequeue'),
        ('images', '0033_merge_20240501_1154'),
    ]

    operations = [
    ]
