# Generated by Django 4.0.6 on 2024-05-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0033_imagequeue'),
        ('images', '0033_merge_20240501_1154'),
    ]

    operations = [
    ]
