# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0034_merge_0033_imagequeue_0033_merge_20240501_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagequeue',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='queue', to='images.image'),
        ),
    ]
