# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-06-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0035_alter_imagequeue_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='context_image_gcloud_paths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='daylight_savings',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='months',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='years',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='time_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload', to='images.timecorrection'),
        ),
    ]
