# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0036_alter_image_context_image_gcloud_paths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dropbox_content_hash',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
