# Generated by Django 4.0.6 on 2024-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0037_alter_image_dropbox_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dropbox_content_hash',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
