# Generated by Django 4.0.6 on 2024-08-10 03:05

from django.db import migrations, models
import images.models.upload


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0038_alter_image_dropbox_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='data_sheet',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='data_sheet',
            field=models.FileField(blank=True, null=True, upload_to=images.models.upload.rename_data_sheet),
        ),
    ]
