# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-09-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0039_historicalupload_data_sheet_upload_data_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='prioritize_tagging_animals',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
