# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-10-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0040_annotator_prioritize_tagging_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagequeue',
            name='partition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
