# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-10-01 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0041_imagequeue_partition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagequeue',
            name='partition',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
