# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2024-10-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0042_alter_imagequeue_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagequeue',
            name='checked_by',
            field=models.ManyToManyField(blank=True, related_name='checked_queue', to='images.annotator'),
        ),
    ]
