# Generated by Django 4.0.6 on 2025-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0043_imagequeue_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
