# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2025-04-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0044_historicalupload_deleted_upload_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='img_count',
            field=models.IntegerField(default=0),
        ),
    ]
