# Generated by Django 4.0.6 on 2025-05-17 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0045_historicalupload_img_count_upload_img_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Subgroup Name')),
            ],
            options={
                'verbose_name_plural': 'Species Subgroups',
                'ordering': ('name', '-created'),
            },
        ),
        migrations.AddField(
            model_name='speciesname',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.speciessubgroup'),
        ),
    ]
