# Generated by Django 4.0.6 on 2025-06-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0046_speciessubgroup_speciesname_subgroup'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='upload',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('dropbox_content_hash',), name='unique_active_dropbox_hash'),
        ),
    ]
