# Generated by Django 4.0.6 on 2025-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0046_speciessubgroup_speciesname_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='dropbox_content_hash',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('dropbox_content_hash',), name='unique_active_dropbox_hash'),
        ),
    ]
