# Generated by Django 4.0.6 on 2025-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0046_speciessubgroup_speciesname_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='use_client_resources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='use_client_resources',
            field=models.BooleanField(default=False),
        ),
    ]
