# Generated by Django 4.0.6 on 2025-06-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0046_speciessubgroup_speciesname_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.bot', unique=True),
        ),
    ]
