# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2025-09-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0047_image_deleted_alter_image_dropbox_content_hash_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('x__gte', 0.0), ('x__lte', 1.0)), name='x_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('y__gte', 0.0), ('y__lte', 1.0)), name='y_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('w__gte', 0.0), ('w__lte', 1.0)), name='w_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('h__gte', 0.0), ('h__lte', 1.0)), name='h_between_0_and_1'),
        ),
    ]
