# Generated by Django 4.2.16 on 2025-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0048_boundingbox_x_between_0_and_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_reported',
            field=models.BooleanField(default=False),
        ),
    ]
