# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.2.16 on 2026-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0049_image_image_reported"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcamerastationaction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical camera station action",
                "verbose_name_plural": "historical camera station actions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalupload",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical upload",
                "verbose_name_plural": "historical uploads",
            },
        ),
        migrations.AlterField(
            model_name="historicalcamerastationaction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalupload",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
