# Generated by Django 4.2.16 on 2025-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0049_image_image_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesname',
            name='speciesnet_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID from SpeciesNet taxonomy for mapping AI detections', null=True, verbose_name='SpeciesNet UUID'),
        ),
    ]
