# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.2.16 on 2026-01-30 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0054_add_species_filter_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalupload",
            name="user_image_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of images reported by user when creating upload",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="user_image_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of images reported by user when creating upload",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
