# Generated by Django 4.2.16 on 2026-02-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0055_alter_historicalupload_user_image_count_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="species",
            new_name="img_spc_modified_idx",
            old_name="images_species_modified_idx",
        ),
        migrations.RenameIndex(
            model_name="species",
            new_name="img_spc_created_idx",
            old_name="images_species_created_idx",
        ),
        migrations.RenameIndex(
            model_name="species",
            new_name="img_spc_name_mod_idx",
            old_name="images_species_name_modified_idx",
        ),
    ]
