# Generated by Django 4.2.16 on 2026-05-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0055_alter_historicalupload_user_image_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="validity",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("INVALID", "Invalid"), ("UNCERTAIN", "Uncertain")],
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="validity",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("INVALID", "Invalid"), ("UNCERTAIN", "Uncertain")],
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="validity",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("INVALID", "Invalid"), ("UNCERTAIN", "Uncertain")],
                db_index=True,
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boundingbox",
            name="validity",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("INVALID", "Invalid"), ("UNCERTAIN", "Uncertain")],
                default="UNCERTAIN",
                max_length=9,
                null=True,
                verbose_name="Validity",
            ),
        ),
    ]
