# Generated by Django 4.2.16 on 2026-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0056_add_validity_to_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="flag_source",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Flagged by annotator"), ("auto_skips", "Auto-flagged")],
                default="",
                help_text="Whether this image was flagged deliberately by an annotator or automatically.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
