# Generated by Django 4.2.16 on 2026-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0056_add_validity_to_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalupload',
            name='processed_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='processed_img_count',
            field=models.IntegerField(default=0),
        ),
    ]
