# Generated by Django 4.2.16 on 2026-08-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0056_add_validity_to_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="flag_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("species_id", "Species ID needs review"),
                    ("bbox_protocol", "Bounding box protocol needs review"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Why the annotator flagged this image for staff review.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="flag_reason_detail",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="image",
            name="flag_source",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Flagged by annotator"), ("auto_skips", "Auto-flagged")],
                default="",
                help_text="Whether this image was flagged deliberately by an annotator or automatically.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flagged_images",
                to="images.annotator",
            ),
        ),
    ]
