# Generated by Django 4.2.16 on 2026-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0056_add_validity_to_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotator",
            name="automation_criteria",
            field=models.CharField(
                blank=True,
                choices=[("single_human", "Single Human")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Automation Criteria",
            ),
        ),
    ]
