# Generated by Django 4.2.16 on 2026-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0057_annotator_automation_criteria"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                condition=models.Q(("deleted", False)),
                fields=["volunteer", "upload_complete"],
                name="upload_pending_by_volunteer",
            ),
        ),
    ]
