# Generated by Django 4.2.16 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0057_annotator_automation_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotator",
            name="total_auto_approved_images",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
