# Generated by Django 4.2.16 on 2026-08-02 16:55

from django.db import migrations
from django.db.models import Count, Q, Sum


def backfill_cached_image_counts(apps, schema_editor):
    Image = apps.get_model("images", "Image")
    Upload = apps.get_model("images", "Upload")
    CameraStation = apps.get_model("locations", "CameraStation")
    MacroSite = apps.get_model("locations", "MacroSite")

    Upload.objects.all().update(img_count=0, processed_img_count=0)
    CameraStation.objects.all().update(total_img_count=0, processed_img_count=0)
    MacroSite.objects.all().update(total_img_count=0, processed_img_count=0)

    upload_counts = Image.objects.values("upload_id").annotate(
        total=Count("id"),
        processed=Count("id", filter=Q(processed=True)),
    )
    for row in upload_counts.iterator():
        Upload.objects.filter(id=row["upload_id"]).update(
            img_count=row["total"],
            processed_img_count=row["processed"],
        )

    station_counts = Upload.objects.values("camera_station_id").annotate(
        total=Sum("img_count"),
        processed=Sum("processed_img_count"),
    )
    for row in station_counts.iterator():
        CameraStation.objects.filter(id=row["camera_station_id"]).update(
            total_img_count=row["total"] or 0,
            processed_img_count=row["processed"] or 0,
        )

    macro_counts = CameraStation.objects.values("micro_site__macro_site_id").annotate(
        total=Sum("total_img_count"),
        processed=Sum("processed_img_count"),
    )
    for row in macro_counts.iterator():
        MacroSite.objects.filter(id=row["micro_site__macro_site_id"]).update(
            total_img_count=row["total"] or 0,
            processed_img_count=row["processed"] or 0,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_camerastation_processed_img_count_and_more"),
        ("images", "0057_historicalupload_processed_img_count_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_cached_image_counts, noop_reverse),
    ]
