# Generated by Django 4.2.16 on 2026-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0057_image_flag_source_image_flagged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="staff_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
