# Generated by Django 4.2.16 on 2026-08-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0058_image_staff_reviewed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagequeue",
            options={"ordering": ("-created",)},
        ),
    ]
