# Generated by Django 4.2.16 on 2026-08-20 22:18

from django.db import migrations, models


def scope_existing_flags_to_all_pipelines(apps, schema_editor):
    """Backfills the per-pipeline review flags for images already in staff review.

    The new fields default to False, so without this every currently flagged image would look
    unflagged to the pipeline queries and drop straight back into both volunteer pools.

    Nothing records which pipeline an existing flag came from -- that is the whole reason these
    fields are being added -- so all of them are scoped to every pipeline. That is exactly what
    the single boolean already meant, so no image changes behaviour on deploy. Flags raised
    after this point are scoped properly by auto_flag_for_staff().
    """
    Image = apps.get_model("images", "Image")

    Image.objects.filter(staff_review_needed=True).update(
        species_review_needed=True,
        activity_review_needed=True,
    )


def unscope_flags(apps, schema_editor):
    """Reverse: the global staff_review_needed boolean is untouched by the forward migration,
    so it still carries the flag state and the per-pipeline columns can simply be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0059_alter_imagequeue_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="activity_review_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="species_review_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(scope_existing_flags_to_all_pipelines, unscope_flags),
    ]
