# Generated by Django 4.2.16 on 2026-08-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0057_annotator_automation_criteria"),
        ("images", "0060_image_activity_review_needed_and_more"),
    ]

    operations = []
