# Generated by Django 4.2.16 on 2026-08-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0060_image_activity_review_needed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagequeue",
            name="image_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="imagequeue",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
