# Generated by Django 4.2.16 on 2026-09-23 02:42

from django.db import migrations


class Migration(migrations.Migration):
    """Rejoins three migration leaves so `migrate` can run again.

    #568 and #565 each branched a 0058 off 0057_annotator_automation_criteria, and
    0061_merge predates both. Three leaves in one app makes every `migrate` and
    `makemigrations` abort with "Conflicting migrations detected" before applying
    anything, so the two 0058s -- and anything added after them -- never reached the
    database. The branches touch different models (annotator, upload, image), so there
    is nothing to reconcile: this is an ordering node only.
    """

    dependencies = [
        ("images", "0058_annotator_total_auto_approved_images"),
        ("images", "0058_upload_upload_pending_by_volunteer"),
        ("images", "0061_merge_20260824_2339"),
    ]

    operations = []
