# Generated by Django 4.2.16 on 2026-08-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0061_imagequeue_image_order_imagequeue_position"),
        ("images", "0061_merge_20260824_2339"),
    ]

    operations = []
