# Generated by Django 4.2.16 on 2026-09-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0058_annotator_total_auto_approved_images'),
        ('images', '0058_upload_upload_pending_by_volunteer'),
        ('images', '0062_merge_20260824_2359'),
    ]

    operations = [
    ]
