# Generated by Django 4.0.2 on 2022-06-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrailtype",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicaltrailsurfacetype",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalmicrosite",
            name="grid",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.grid",
                verbose_name="Grid name",
            ),
        ),
        migrations.AddField(
            model_name="historicalmicrosite",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalmicrosite",
            name="macro_site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.macrosite",
            ),
        ),
        migrations.AddField(
            model_name="historicalmacrosite",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.county",
            ),
        ),
        migrations.AddField(
            model_name="historicalmacrosite",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicallandusetype",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalhabitattype",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalgrid",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalcounty",
            name="area",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.area",
            ),
        ),
        migrations.AddField(
            model_name="historicalcounty",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="historicalarea",
            name="history_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="area",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="locations.area"),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="camera",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.camera",
                verbose_name="Felidae camera serial number (if applicable)",
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="habitat_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_habitat_type",
                to="locations.habitattype",
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="land_use_type",
            field=models.ManyToManyField(blank=True, to="locations.LandUseType"),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="micro_site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="locations.microsite"),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="padlock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.padlock",
                verbose_name="Padlock type (if applicable)",
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="python_lock",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.pythonlock",
                verbose_name="Python lock (if applicable)",
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="secondary_habitat_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_habitat_type",
                to="locations.habitattype",
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="trail_surface",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="locations.trailsurfacetype"
            ),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="trail_type",
            field=models.ManyToManyField(blank=True, to="locations.TrailType"),
        ),
        migrations.AddField(
            model_name="camerastation",
            name="volunteer",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
