# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.2 on 2022-06-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camerastation",
            name="habitat_type",
        ),
        migrations.RemoveField(
            model_name="camerastation",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="camerastation",
            name="picture_instructions",
        ),
        migrations.RemoveField(
            model_name="camerastation",
            name="secondary_habitat_type",
        ),
        migrations.AddField(
            model_name="camerastation",
            name="habitat_types",
            field=models.ManyToManyField(blank=True, to="locations.HabitatType"),
        ),
        migrations.AddField(
            model_name="habitattype",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Additional notes"),
        ),
        migrations.AddField(
            model_name="historicalhabitattype",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Additional notes"),
        ),
        migrations.AlterField(
            model_name="camerastation",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Instructions/Comments"),
        ),
        migrations.RemoveField(
            model_name="camerastation",
            name="trail_type",
        ),
        migrations.AddField(
            model_name="camerastation",
            name="trail_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="locations.trailtype"
            ),
        ),
        migrations.RemoveField(
            model_name="camerastation",
            name="volunteer",
        ),
        migrations.AddField(
            model_name="camerastation",
            name="volunteer",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="microsite",
            name="grid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.grid",
                verbose_name="Grid name",
            ),
        ),
    ]
