# Generated by Django 4.0.6 on 2022-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_historicalarea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarea',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical area'},
        ),
        migrations.AlterModelOptions(
            name='historicalcounty',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical county'},
        ),
        migrations.AlterModelOptions(
            name='historicalgrid',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical grid'},
        ),
        migrations.AlterModelOptions(
            name='historicalhabitattype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical habitat type'},
        ),
        migrations.AlterModelOptions(
            name='historicallandusetype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical land use type'},
        ),
        migrations.AlterModelOptions(
            name='historicalmacrosite',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical macro site'},
        ),
        migrations.AlterModelOptions(
            name='historicalmicrosite',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical micro site'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrailsurfacetype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trail surface type'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrailtype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trail type'},
        ),
        migrations.AlterField(
            model_name='historicalarea',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcounty',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalgrid',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalhabitattype',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicallandusetype',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalmacrosite',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalmicrosite',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltrailsurfacetype',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltrailtype',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
