# Generated by Django 4.2.16 on 2026-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_historicalarea_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalarea",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical area",
                "verbose_name_plural": "historical areas",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcounty",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical county",
                "verbose_name_plural": "historical Counties",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgrid",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical grid",
                "verbose_name_plural": "historical grids",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhabitattype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical habitat type",
                "verbose_name_plural": "historical habitat types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallandusetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical land use type",
                "verbose_name_plural": "historical land use types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmacrosite",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical macro site",
                "verbose_name_plural": "historical macro sites",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmicrosite",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical micro site",
                "verbose_name_plural": "historical micro sites",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltrailsurfacetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical trail surface type",
                "verbose_name_plural": "historical trail surface types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltrailtype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical trail type",
                "verbose_name_plural": "historical trail types",
            },
        ),
        migrations.AlterField(
            model_name="historicalarea",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcounty",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalgrid",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhabitattype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallandusetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmacrosite",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmicrosite",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltrailsurfacetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltrailtype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
