# Generated by Django 4.2.16 on 2026-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_add_query_optimization_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerastation',
            name='processed_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camerastation',
            name='total_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmacrosite',
            name='processed_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmacrosite',
            name='total_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='macrosite',
            name='processed_img_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='macrosite',
            name='total_img_count',
            field=models.IntegerField(default=0),
        ),
    ]
