path: ./
train: ./wildepod/images/train/
test: ./wildepod/images/test/
val: ./wildepod/images/val/

nc: 76

names: 
  0: 'Acorn Woodpecker'
  1: 'American Badger'
  2: 'American crow'
  3: 'American Robin'
  4: 'Barn owl'
  5: 'Bat (any species)'
  6: 'Black bear'
  7: 'Black-tailed jackrabbit'
  8: 'Bobcat'
  9: 'Brush rabbit'
  10: 'Burrowing Owl'
  11: 'California Quail'
  12: 'California Thrasher'
  13: 'California Towhee'
  14: 'Canada Goose'
  15: 'Common raven'
  16: 'Cottontail rabbit'
  17: 'Cow, Cattle'
  18: 'Coyote'
  19: 'Cyclist'
  20: 'Dark-eyed Junco'
  21: 'Domestic cat'
  22: 'Domestic dog'
  23: 'Domestic horse'
  24: 'Duck species'
  25: 'Eastern grey squirrel'
  26: 'Electric Bicycle'
  27: 'Elk or deer- Consider flagging for staff 1st'
  28: 'Goat (domestic)'
  29: 'Golden Eagle'
  30: 'Gray fox'
  31: 'Great horned owl'
  32: 'Horse rider'
  33: 'House finch'
  34: 'Human'
  35: 'invertebrate'
  36: 'Long-tailed Weasel'
  37: 'Merriam’s Chipmunk'
  38: 'Motorized vehicle'
  39: 'Mourning dove'
  40: 'Mule deer'
  41: 'Non motorized vehicle (bike)'
  42: 'Northern Band-tailed Pigeon'
  43: 'Northern Flicker'
  44: 'prey-bird'
  45: 'prey-mammal'
  46: 'prey-unknown'
  47: 'Puma'
  48: 'Raccoon'
  49: 'Red fox'
  50: 'Red-Shouldered Hawk'
  51: 'Red-tailed hawk'
  52: 'reptile (any species)'
  53: 'River otter'
  54: 'Sheep (domestic)'
  55: 'Spotted Skunk'
  56: 'Spotted Towhee'
  57: 'Steller’s Jay'
  58: 'Striped Skunk'
  59: 'Tule Elk'
  60: 'Turkey'
  61: 'Turkey Vulture'
  62: 'Unknown'
  63: 'Unknown bird species'
  64: 'Unknown hawk'
  65: 'Unknown mouse or rat spp'
  66: 'Unknown Nightjar'
  67: 'Unknown owl species'
  68: 'Unknown Rabbit spp'
  69: 'Unknown squirrel spp'
  70: 'Virginia Opossum'
  71: 'Western Blue Bird'
  72: 'Western grey squirrel'
  73: 'Western Screech owl'
  74: 'Western scrub-jay'
  75: 'Wild Boar'
