# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2022-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_historicalbox_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbox',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical box'},
        ),
        migrations.AlterModelOptions(
            name='historicalcamera',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Camera'},
        ),
        migrations.AlterModelOptions(
            name='historicalcamerabrand',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical camera brand'},
        ),
        migrations.AlterModelOptions(
            name='historicalcameramodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical camera model'},
        ),
        migrations.AlterModelOptions(
            name='historicalpadlock',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical padlock'},
        ),
        migrations.AlterModelOptions(
            name='historicalpythonlock',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical python lock'},
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcamera',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcamerabrand',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcameramodel',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpadlock',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpythonlock',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
