# Generated by Django 4.2.16 on 2025-12-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_historicalbox_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbox',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical box', 'verbose_name_plural': 'historical Boxes'},
        ),
        migrations.AlterModelOptions(
            name='historicalcamera',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Camera', 'verbose_name_plural': 'historical Camera Inventory'},
        ),
        migrations.AlterModelOptions(
            name='historicalcamerabrand',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical camera brand', 'verbose_name_plural': 'historical camera brands'},
        ),
        migrations.AlterModelOptions(
            name='historicalcameramodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical camera model', 'verbose_name_plural': 'historical camera models'},
        ),
        migrations.AlterModelOptions(
            name='historicalpadlock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical padlock', 'verbose_name_plural': 'historical padlocks'},
        ),
        migrations.AlterModelOptions(
            name='historicalpythonlock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical python lock', 'verbose_name_plural': 'historical python locks'},
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcamera',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcamerabrand',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcameramodel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpadlock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpythonlock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
