# Generated by Django 4.0.6 on 2023-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
