# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Generated by Django 4.0.6 on 2023-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser_is_expert_user_is_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Expert user votes directly validate Category, Species and Activity without need for additional consensus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Expert user votes directly validate Category, Species and Activity without need for additional consensus'),
        ),
    ]
