# Generated by Django 4.2.16 on 2026-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_historicaluser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="last_review_visit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="previous_review_visit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_review_visit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="previous_review_visit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
