# Copyright (c) 2026 Felidae Conservation Fund info@felidaefund.org
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from django.urls import path

from .views import (
    ActivityAnnotationProcessorView,
    AnnotateActivityView,
    AnnotateSpeciesView,
    ApplyTimeCorrectionView,
    BulkImageActionView,
    ChangeAnnotationView,
    CheckDropbox2FAEmailView,
    CreatePrecomputedQueueView,
    CustomAnnotationView,
    DeleteAnnotationView,
    FixUploadSetsView,
    GetRecentTagsView,
    ImageDetailView,
    ModifyUploadSetImagesView,
    PrecomputeImageQueuesView,
    PreviewTimeCorrectionsView,
    SavePreviousImageToReturnToView,
    SaveRecentTagsView,
    SearchImagesView,
    SetImageQueuePartitionView,
    SpeciesAnnotationProcessorView,
    TimeCorrectionCreateView,
    TimeCorrectionStatusView,
    UploadCompleteView,
    UploadCreateView,
    UploadDeleteView,
    UploadDetailView,
    UploadListView,
    UploadResumeProcessingView,
    UploadStatusView,
)

urlpatterns = [
    path("uploads/", UploadListView.as_view(), name="list_uploads"),
    path(
        "uploads/status/",
        UploadStatusView.as_view(),
        name="upload_status",
    ),
    path(
        "uploads/resume-processing/",
        UploadResumeProcessingView.as_view(),
        name="upload_resume_processing",
    ),
    path("upload/", UploadCreateView.as_view(), name="create_upload"),
    path("upload/<uuid:pk>/", UploadDetailView.as_view(), name="view_upload"),
    path(
        "upload/<uuid:pk>/complete",
        UploadCompleteView.as_view(),
        name="complete_upload",
    ),
    path(
        "upload/<uuid:pk>/create_time_correction",
        TimeCorrectionCreateView.as_view(),
        name="create_time_correction",
    ),
    path(
        "upload/<uuid:pk>/apply_time_correction",
        ApplyTimeCorrectionView.as_view(),
        name="apply_time_correction",
    ),
    path(
        "upload/delete",
        UploadDeleteView.as_view(),
        name="delete_upload",
    ),
    # path("upload/<uuid:pk>/export/", UploadExportView.as_view(), name="export_upload"),
    path("image/<uuid:pk>", ImageDetailView.as_view(), name="image"),
    path("annotate/species", AnnotateSpeciesView.as_view(), name="annotate_species"),
    path(
        "annotate/species/staff_review",
        AnnotateSpeciesView.as_view(),
        name="staff_annotate_species",
        kwargs={"staff_review": True},
    ),
    path(
        "annotate/species/reported_images",
        AnnotateSpeciesView.as_view(),
        name="reported_images_annotate_species",
        kwargs={"reported_images": True},
    ),
    path(
        "annotate/species/searched",
        AnnotateSpeciesView.as_view(),
        name="searched_annotate_species",
        kwargs={"searched": True},
    ),
    path(
        "annotate/custom_annotation",
        CustomAnnotationView.as_view(),
        name="custom_annotation",
    ),
    path(
        "annotate/activity/<str:category>",
        AnnotateActivityView.as_view(),
        name="annotate_activity",
    ),
    path(
        "queue/create/",
        CreatePrecomputedQueueView.as_view(),
        name="create_precomputed_queue",
    ),
    path(
        "bulk-action/",
        BulkImageActionView.as_view(),
        name="bulk_image_action",
    ),
    path(
        "queue/precompute/",
        PrecomputeImageQueuesView.as_view(),
        name="precompute_queues",
    ),
    path(
        "species-annotation-processor/",
        SpeciesAnnotationProcessorView.as_view(),
        name="species_annotation_processor",
    ),
    path(
        "activity-annotation-processor/",
        ActivityAnnotationProcessorView.as_view(),
        name="activity_annotation_processor",
    ),
    path(
        "set-queue-partition/",
        SetImageQueuePartitionView.as_view(),
        name="set_queue_partition",
    ),
    path(
        "get-recent-tags/",
        GetRecentTagsView.as_view(),
        name="get_recent_tags",
    ),
    path(
        "save-previous-image-to-return-to/",
        SavePreviousImageToReturnToView.as_view(),
        name="save_previous_image_to_return_to",
    ),
    path(
        "save-recent-tags/",
        SaveRecentTagsView.as_view(),
        name="save_recent_tags",
    ),
    path(
        "search_images/",
        SearchImagesView.as_view(),
        name="search_images",
    ),
    path(
        "staff-change-annotation/",
        ChangeAnnotationView.as_view(),
        name="staff_change_annotation",
    ),
    path(
        "staff-delete-annotation/",
        DeleteAnnotationView.as_view(),
        name="staff_delete_annotation",
    ),
    path(
        "uploads/fix/",
        FixUploadSetsView.as_view(),
        name="fix_upload_sets",
    ),
    path(
        "modify-upload-set-images",
        ModifyUploadSetImagesView.as_view(),
        name="modify_upload_set_images",
    ),
    path(
        "preview-time-corrections",
        PreviewTimeCorrectionsView.as_view(),
        name="preview_time_corrections",
    ),
    path(
        "time-correction-status",
        TimeCorrectionStatusView.as_view(),
        name="time_correction_status",
    ),
    path(
        "uploads/check-dropbox-2fa-email/",
        CheckDropbox2FAEmailView.as_view(),
        name="check_dropbox_2fa_email",
    ),
]
