path: ./
train: ./wildepod/images/train/
test: ./wildepod/images/test/
val: ./wildepod/images/val/

nc: 69

names: 
  0: 'Acorn Woodpecker'
  1: 'American Badger'
  2: 'American crow'
  3: 'American Robin'
  4: 'Black bear'
  5: 'Black-tailed jackrabbit'
  6: 'Bobcat'
  7: 'Brush rabbit'
  8: 'Burrowing Owl'
  9: 'California Quail'
  10: 'California Thrasher'
  11: 'California Towhee'
  12: 'Canada Goose'
  13: 'Common raven'
  14: 'Cottontail rabbit'
  15: 'Cow, Cattle'
  16: 'Coyote'
  17: 'Cyclist'
  18: 'Dark-eyed Junco'
  19: 'Domestic cat'
  20: 'Domestic dog'
  21: 'Domestic horse'
  22: 'Duck species'
  23: 'Eastern grey squirrel'
  24: 'Electric Bicycle'
  25: 'Elk or deer- Consider flagging for staff 1st'
  26: 'Goat (domestic)'
  27: 'Golden Eagle'
  28: 'Gray fox'
  29: 'Great horned owl'
  30: 'Horse rider'
  31: 'House finch'
  32: 'Human'
  33: 'invertebrate'
  34: 'Long-tailed Weasel'
  35: 'Merriam’s Chipmunk'
  36: 'Motorized vehicle'
  37: 'Mourning dove'
  38: 'Mule deer'
  39: 'Non motorized vehicle (bike)'
  40: 'Northern Band-tailed Pigeon'
  41: 'Northern Flicker'
  42: 'Puma'
  43: 'Raccoon'
  44: 'Red fox'
  45: 'Red-Shouldered Hawk'
  46: 'Red-tailed hawk'
  47: 'reptile (any species)'
  48: 'River otter'
  49: 'Sheep (domestic)'
  50: 'Spotted Skunk'
  51: 'Spotted Towhee'
  52: 'Steller’s Jay'
  53: 'Striped Skunk'
  54: 'Tule Elk'
  55: 'Turkey'
  56: 'Turkey Vulture'
  57: 'Unknown'
  58: 'Unknown bird species'
  59: 'Unknown mouse or rat spp'
  60: 'Unknown owl species'
  61: 'Unknown Rabbit spp'
  62: 'Unknown squirrel spp'
  63: 'Virginia Opossum'
  64: 'Western Blue Bird'
  65: 'Western grey squirrel'
  66: 'Western Screech owl'
  67: 'Western scrub-jay'
  68: 'Wild Boar'
